### PR TITLE
Fix 8-digit hexadecimal color code compression exception

### PR DESCRIPTION
**Pull request by 1123612483**
#40 I deal with this issue.@PureKrome

### CODE REVIEW

**Comment by PureKrome** [comment]
Thanks heaps @1123612483 for the PR!! 

could you please provide a unit test with various test conditions, please?

**Comment by 1123612483** [comment]
> Thanks heaps @1123612483 for the PR!!
> 
> could you please provide a unit test with various test conditions, please?

OK, wait for me to create a PR.

**Comment by PureKrome** [comment]
> OK, wait for me to create a PR.

No need! just update this current PR 👍🏻 🍰

**Comment by 1123612483** [comment]
> > OK, wait for me to create a PR.
> 
> No need! just update this current PR 👍🏻 🍰

I added a test condition, please help check.@PureKrome

**Review by PureKrome — APPROVED** [review]
🍰

**Pull request merged**
